
title: libtrackerboy
baseurl: /libtrackerboy
description: >-
  Support library for Trackerboy, also known as the back end of Trackerboy.

sass:
  # drop this line when upgrading jekyll-sass-converter to v3.x.x
  implementation: sass-embedded
  # do not include source maps for production builds
  sourcemap: development

collections:
  releases:
    output: true
    permalink: /:collection/:path/
    sort_by: date

github: [metadata]

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - ci.py
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
