== Module Piece Format [[module-piece-format]]

Module piece files contain a single part of a module, for easy reuse and
sharing. A piece file can contain either a song ($$*$$.tbs), an instrument
($$*$$.tbi) or a waveform ($$*$$.tbw).

=== Structure

A piece file consists of a header followed by a payload. The payload is a
single INST, SONG or WAVE block. A terminator is not used since there is only
one block present in the payload.

.Structure of a module piece file
image::res/fig-piece-structure-1.svg[]

=== Header

The Header for a piece file is the same as the module one, but a reduced
variant. This reduced header contains only the signature, version and revision
fields, or bytes 0-25. The fields are exactly the same as the module format,
see the previously defined Header format for more info.

=== Payload

The payload is a single INST block for $$*$$.tbi files, a single SONG block for
$$*$$.tbs files or a single WAVE block for $$*$$.tbw files.

The format of these blocks are the same as the ones used in the module file
format except for one key detail: the id is omitted for INST and WAVE blocks.

NOTE: INST and WAVE blocks will be 1 byte less than their module counterpart,
      since the Id is omitted.
