:tbm-rev-major: 2
:draft-target-version: libtrackerboy v0.8.0
include::include/title.adoc[]

<<<

include::include/introduction.adoc[]

== Changes

Major 2 introduces the following changes to the format:

* Added a `Float32` type to the specification.
* The `customFramerate` field in the header is now a `Float32` instead of `Uint16`.
* Added `systemOverride` and `customFramerateOverride` fields to the 
  `SongFormat` record.
* Replaced the initial envelope setting with a sequence in INST blocks
** Added a new sequence to INST blocks, `skEnvelope`
** Replaced the `InstrumentFormat` record with a single `Uint8` byte being the
   channel setting

This allows for two new features: per-song timing and envelope sequences.

<<<

include::include/definitions-1.adoc[]

include::include/file-extensions-1.adoc[]

<<<

== Basic Types

Below are basic data types used throughout the format

[cols="2,2,6"]
|===
| Type name   | Size (bytes) | Description
| Uint8       | 1            | Unsigned 8-bit integer (0-255)                                 
| BiasedUint8 | 1            | Unsigned 8-bit integer, biased form (1-256)
| Char        | 1            | 8-bit Character type                          
| Bool        | 1            | Boolean as an uint8 (0 for false, nonzero for true)                  
| Uint16      | 2            | Unsigned 16-bit integer, in little endian (0-65536)                  
| Uint32      | 4            | Unsigned 32-bit integer, in little endian                            
| LString     | 2 + _length_ | Length-prefixed UTF-8 string, string data prefixed by a Uint16 _length_
| Float32     | 4            | IEEE 754 single-precision floating point number
|===

<<<

include::include/error-codes-1.adoc[]

<<<

== Structure

A TrackerBoy module consists of a Header and a Payload.

```
   +----------------+-----------------------------------------+------------+
   |                |                                         |            |
   | Header         | Payload                                 | Terminator |
   | 160 bytes      | size varies                             | 12 bytes   |
   |                |                                         |            |
   +----------------+-----------------------------------------+------------+
  +0              +160                                                      EOF
```

<<<

== Header

The figure below defines the Header structure used in all file types. All
multi-byte fields are stored in little-endian. The size of the header is a
fixed 160 bytes, with any unused space marked as reserved. Reserved fields can
be utilized for future revisions of the format. Reserved fields should be set
to zero, but this is not enforced.

The layout of the header depends on the header revision, located in offset 24.
The current revision of the header is shown below.

```
      +0         +1         +2        +3
  0   +-------------------------------------------+
      |                                           |
      | signature ( TRACKERBOY )                  |
      |                                           |
  12  +-------------------------------------------+
      | version major                             |
  16  +-------------------------------------------+
      | version minor                             |
  20  +-------------------------------------------+
      | version patch                             |
  24  +----------+----------+---------------------+
      | m. rev   | n. rev   | reserved            |
  28  +----------+----------+---------------------+
      |                                           |
      |                                           |
      |                                           |
      | title                                     |
      |                                           |
      |                                           |
      |                                           |
      |                                           |
  60  +-------------------------------------------+
      |                                           |
      |                                           |
      |                                           |
      | artist                                    |
      |                                           |
      |                                           |
      |                                           |
      |                                           |
  92  +-------------------------------------------|
      |                                           |
      |                                           |
      |                                           |
      | copyright                                 |
      |                                           |
      |                                           |
      |                                           |
      |                                           |
  124 +-------------------------------------------+
      | icount   | scount   | wcount   | system   |
  128 +----------+----------+----------+----------+
      | customFramerate                           |
      +-------------------------------------------+
      |                                           |
      |                                           |
      |                                           |
      | reserved                                  |
      |                                           |
      |                                           |
      |                                           |
      |                                           |
  160 +-------------------------------------------+
```

<<<

[cols="1,1,2,6"]
|===
| Offset | Size | Type        | Field name
| +0     | 12   | Char[12]    | signature
| +12    | 4    | Uint32      | versionMajor
| +16    | 4    | Uint32      | versionMinor
| +20    | 4    | Uint32      | versionPatch
| +24    | 1    | Uint8       | m. rev
| +25    | 1    | Uint8       | n. rev
| +26    | 2    | Char[2]     | reserved
| +28    | 32   | Char[32]    | title
| +60    | 32   | Char[32]    | artist
| +92    | 32   | Char[32]    | copyright
| +124   | 1    | Uint8       | icount
| +125   | 1    | BiasedUint8 | scount
| +126   | 1    | Uint8       | wcount
| +127   | 1    | Uint8       | system
| +128   | 4    | Float32     | customFramerate
| +132   | 28   | Char[28]    | reserved
|===

include::include/signature.adoc[]

include::include/header-version.adoc[]

include::include/header-major-minor.adoc[]

include::include/header-author-info.adoc[]

include::include/header-counts.adoc[]

include::include/header-system.adoc[]

include::include/header-reserved.adoc[]

<<<

== Payload

The payload is located right after the header (offset 160). It contains a
variable number of "blocks" or tagged data with a size.

include::include/payload-blocks.adoc[]

include::include/payload-block-details-1.adoc[]

<<<

include::include/payload-comm.adoc[]

<<<

=== SONG block format

A SONG block contains the data for a single song in the module. Songs are
stored in the same order as they were in the module's song list. The first
song block is song #0 and so on.

Song data is composed of the following, in this order:

1. The name, `LString`
2. A `SongFormat` record
3. The song order, as an array of `OrderRow` or `Char[4][patternCount]`
4. The track data, as a sequence of `TrackFormat` and `RowFormat` records

==== Song name

The first part of a SONG block is the song's name, as an `LString`.

==== SongFormat

Following the name is a `SongFormat` record:

[cols="1,1,2,6"]
|===
| Offset | Size | Type        | Field name
| +0     | 1    | BiasedUint8 | rowsPerBeat            
| +1     | 1    | BiasedUint8 | rowsPerMeasure         
| +2     | 1    | Uint8       | speed                  
| +3     | 1    | BiasedUint8 | patternCount           
| +4     | 1    | BiasedUint8 | rowsPerTrack           
| +5     | 2    | Uint16      | numberOfTracks
| +7     | 1    | Uint8       | numberOfEffects
| +8     | 1    | Uint8       | systemOverride
| +9     | 4    | Float32     | customFramerateOverride
|===

rowsPerBeat:: number of rows that make up a beat, used by the front end
for highlighting and tempo calculation.
rowsPerMeasure:: number of rows that make up a measure, used by the front
end for highlighting.
speed:: Initial speed setting for the song in Q4.4 format
[#SongFormat-patternCount]
patternCount:: number of patterns for the song
rowsPerTrack:: the size, in rows, of a track (all tracks have the same size).
numberOfTracks:: number of tracks stored in this song block.
numberOfEffects:: 
  this byte contains the number of effect columns visible for each channel.
  Each count ranges from 1-3 and is stored as a 2 bit number in this byte. Bits
  0-1 are the count for CH1, bits 2-3 are the count for CH2 and so on. 
+
NOTE: This value is for UI purposes only and has no effect on playback!

systemOverride::
This byte determines if the song should use a different tick rate than the one
specified in the module. The following table shows all possible values:
+
[cols="1,2,7"]
|===
| Value | System       | Description
| 0     | N/A          | Use the module's system setting (default)
| 1     | systemDmg    | Force DMG system
| 2     | systemSgb    | Force SGB system
| 3     | systemCustom | Force custom framerate using `customFramerateOverride` field.
|===
customFramerateOverride:: The custom framerate to use if `systemOverride` was
                          set to `3`. This value must be a positive number.

==== Song Order

Next is the song order, an array of `OrderRow` records with the dimension being
the <<SongFormat-patternCount,patternCount>> field from the song format record.
An `OrderRow` record is a set of 4 `Uint8` track ids, with the first being the
track id for channel 1 and the last being the id for channel 4.

==== Track Data

Finally, the rest of the block contains the pattern data for every track in the
song. Each track gets its own `TrackFormat` record and an array of `RowFormat`
records.

The `TrackFormat` record:

[cols="1,1,2,6"]
|===
| Offset | Size | Type        | Field name
| +0     | 1    | Uint8       | channel
| +1     | 1    | Uint8       | trackId
| +2     | 1    | BiasedUint8 | rows
|===

channel:: determines which channel the track is for. _Valid values 0-3_.
trackId:: determines the track id to use for this track
rows:: the number of RowFormat records that follow this structure

The `RowFormat` record:

[cols="1,1,2,6"]
|===
| Offset | Size | Type     | Field name
| +0     | 1    | Uint8    | rowno
| +1     | 8    | TrackRow | rowdata
|===

rowno:: the index in the track's row array to set
rowdata:: 
the data to set at this index, where the `TrackRow` type is:
+
[cols="1,1,2,6"]
|===
| Offset | Size | Type        | Field name
| +0     | 1    | Uint8       | note
| +1     | 1    | Uint8       | instrument
| +2     | 6    | Effect[3]   | effects
|===
+
with `Effect` being:
+
[cols="1,1,2,6"]
|===
| Offset | Size | Type        | Field name
| +0     | 1    | Uint8       | effectType
| +1     | 1    | Uint8       | effectParam
|===
+
and `effectType` should be any of the following:
+
[cols="1,2,7"]
|===
| Value | Effect Syntax | Identifier       
| 0     | ---           | etNoEffect       
| 1     | Bxx           | etPatternGoto    
| 2     | C00           | etPatternHalt    
| 3     | Dxx           | etPatternSkip    
| 4     | Fxy           | etSetTempo       
| 5     | Txx           | etSfx            
| 6     | Exx           | etSetEnvelope    
| 7     | V0x           | etSetTimbre      
| 8     | I0x           | etSetPanning     
| 9     | Hxx           | etSetSweep       
| 10    | Sxx           | etDelayedCut     
| 11    | Gxx           | etDelayedNote    
| 12    | L00           | etLock           
| 13    | 0xy           | etArpeggio       
| 14    | 1xx           | etPitchUp        
| 15    | 2xx           | etPitchDown      
| 16    | 3xx           | etAutoPortamento 
| 17    | 4xy           | etVibrato        
| 18    | 5xx           | etVibratoDelay   
| 19    | Pxx           | etTuning         
| 20    | Qxy           | etNoteSlideUp    
| 21    | Rxy           | etNoteSlideDown  
| 22    | Jxy           | etSetGlobalVolume
|===

The last `RowFormat` record for the last track ends the `SONG` block.

<<<

=== INST block format

An INST block contains the data for a single instrument. The data is
structured in this order:

. The instrument's id, `Uint8`
. The instrument's name, `LString`
. The instrument's channel, `Uint8`
. 5 sequences each composed of:
.. A `SequenceFormat` record
.. The sequence's data

==== Id and Name

The `INST` block data begins with a 1 byte id (0-63), followed by an `LString`
name.

NOTE: `WAVE` blocks also begin with an id and name in the same format.

==== Channel

Next is a single byte representing the instrument's channel setting. This byte
must be either 0, 1, 2 or 3 for CH1, CH2, CH3, CH4, respectively.

NOTE: Instruments can be used on any channel, this setting is only used for
      previewing on the set channel, as well as organizational purposes.

==== Sequence data

Following the InstrumentFormat record is the sequence data for each of the
instrument's sequences. Data for a sequence is structured as a `SequenceFormat`
record followed by the sequence data. There are five kinds of sequences for
every instrument. The kind of sequence the data is for is determined by its
order in the block:

[cols="1,9"]
|===
| Order | SequenceKind
| 0     | skArp
| 1     | skPanning
| 2     | skPitch
| 3     | skTimbre
| 4     | skEnvelope
|===

The `SequenceFormat` record:

[cols="1,1,2,6"]
|===
| Offset | Size | Type   | Field name
| +0     | 2    | Uint16 | length
| +2     | 1    | Bool   | loopEnabled
| +3     | 1    | Uint8  | loopIndex
|===

length:: The length of the sequence data. Following this record will be this
         number of `Uint8` bytes that are the sequence's data.
         _Valid values 0-256_.
loopEnabled:: Determines if this sequence has a loop index.
loopIndex:: The index of the loop point.

<<<

include::include/payload-wave-1.adoc[]

<<<

include::include/terminator-eof.adoc[]

<<<

include::include/module-piece-format.adoc[]

<<<

== Upgrading

When upgrading a major 1 module to major 2, use the following guidelines:

* The header's customFramerate field can be safely casted to a Float32 if
  set.
* Existing SONG blocks should assume values of `0` for `systemOverride` and
  `0.0f` for `customFramerateOverride` fields in the `SongFormat` record.
* The initial envelope setting in INST blocks can easily be converted to an
  envelope sequence via:
** an empty sequence when `initEnvelope` was `0`
** a sequence with 1 value when `initEnvelope` was `1`, with that value being 
  `envelope`.
