
name: '[push] [develop] Build'
on:
  push:
    branches:
      - develop
    tags-ignore: '**'
    paths:
      - 'libtrackerboy/**'
      - 'tests/**'
      - 'libtrackerboy.nim'
      - 'libtrackerboy.nimble'
      - '.github/workflows/build.yml'
      

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nim-version: ['stable', 'devel']
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('libtrackerboy.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}

      - name: check package
        run: nimble check

      - name: setup
        run: |
          nim setDev
          nimble install -d -y
          nimble setup
      
      - name: test
        run: nim test

      - name: endian tests
        run: nim endianTests
