
name: build
on:
  push:
    branches:
      - develop
    tags-ignore: '**'
    paths:
      - 'libtrackerboy/**'
      - 'tests/**'
      - 'libtrackerboy.nim'
      - 'libtrackerboy.nimble'
      

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # ignore devel for now, not ready for Nim 2.0.0 just yet
        nim-version: ['stable'] #, 'devel']
    steps:

      - uses: actions/checkout@v3
      
      - uses: lukka/get-cmake@latest

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}

      - name: dependencies
        run: ./nut init

      - name: check
        run: ./nut check

      - name: test
        run: ./nut test

      - name: endian tests
        run: ./nut endianTests
