
name: '[push] [develop] Build'
on:
  push:
    branches:
      - develop
    tags-ignore: '**'
    paths:
      - 'libtrackerboy/**'
      - 'tests/**'
      - 'libtrackerboy.nim'
      - 'libtrackerboy.nimble'
      

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nim-version: ['stable', 'devel']
    steps:

      - uses: actions/checkout@v3
      
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}

      - name: dependencies
        run: nimble install -y --depsOnly

      - name: check
        run: nimble check

      - name: test
        run: nimble test

      - name: endian tests
        run: nimble endianTests
