
name: build
on:
  push:
    branches:
      - main
      - develop
    tags-ignore: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: lukka/get-cmake@latest

      - name: Install dependencies (Catch2)
        run: |
          cd ../
          git clone https://github.com/catchorg/Catch2
          cd Catch2
          git checkout tags/v2.13.7
          mkdir build
          cmake -S . -B build -H. -DBUILD_TESTING=OFF
          sudo cmake --build build --target install
      
      - name: Build
        run: |
          cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Debug -DLIBTRACKERBOY_ENABLE_UNITY=ON
          cmake --build build --target all

      - name: Test
        run: |
          cd build
          ctest
