
name: build
on:
  push:
    branches:
      - develop
    tags-ignore: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nim-version: ['stable', 'devel']
    steps:

      - uses: actions/checkout@v2

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}

      - name: dependencies
        run: nimble install -y --depsOnly

      - name: check
        run: nimble check

      - name: test
        run: nimble tester && bin/tester

      - name: endian tests
        run: nimble endianTests
