
name: '[push] [develop] Build'
on:
  push:
    branches:
      - develop
    tags-ignore: '**'
    paths:
      - 'libtrackerboy/**'
      - 'tests/**'
      - 'libtrackerboy.nim'
      - 'libtrackerboy.nimble'
      - '.github/workflows/build.yml'
      

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nim-version: ['stable', 'devel']
    steps:
      
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}

      - name: Setup workspace
        run: |
          ln -s $(choosenim show path)/bin/atlas $HOME/.nimble/bin/atlas
          mkdir workspace
          cd workspace
          atlas init

      - uses: actions/checkout@v4
        with:
          path: "workspace/libtrackerboy"

      - name: Dependencies
        run: |
          cd workspace/libtrackerboy
          atlas install libtrackerboy.nimble
          nim setup

      - name: check package
        run: nimble check
      
      - name: test
        run: nim test

      - name: endian tests
        run: nim endianTests
