name: '[push] [develop] Documentation'
on:
  push:
    branches:
      - develop
    tags-ignore: '**'
    paths:
      - 'libtrackerboy/**'
      - 'libtrackerboy.nim'
      - 'docs/**'

jobs:
  build:
    name: 'Generate and upload documentation'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - uses: actions/checkout@v3

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install asciidoctor
        run: |
          sudo apt update
          sudo apt install -y asciidoctor ruby-asciidoctor-pdf

      - name: Generate documentation
        run: |
          nimble install -y --depsOnly
          nim docs
          nim docsSpecs

      - name: Clone gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0
          token: ${{ secrets.LIBTRACKERBOY_PAT }}
      
      - name: Upload documentation
        run: |
          cd gh-pages
          ./ci.py develop ../htmldocs
          git add .
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git commit -a -m "github-actions: update docs for develop branch"
          git push origin gh-pages
