name: releases
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: The tag name to run this workflow for
        required: true
        type: string

jobs:
  draft-release:
    name: Draft github release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Get version (from dispatch)
        id: get-version
        if: inputs.tag != ''
        run: echo "::set-output name=version::${{ inputs.tag }}"
      
      - name: Get version (from pushed tag)
        if: steps.get-version.conclusion == 'skipped'
        run: echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"
      
      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Make sure the generated documentation for this version was uploaded,
            then put the changes for this version from CHANGELOG.md here and
            publish.

            If the build fails, delete this tag and draft and try again after
            fixing the issue.
          draft: true
          name: libtrackerboy ${{ steps.get-version.outputs.version }}
          prerelease: ${{ startsWith( 'v0.', steps.get-version.outputs.version ) }}

  release:
    name: Generate documentation for the release and upload
    needs: draft-release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Generate documentation
        run: ./nut docgen ${{ needs.draft-release.outputs.version }}
      
      - name: Clone gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0
      
      - name: Upload documentation
        run: |
          cd gh-pages
          ./ci.py release ../htmldocs ${{ needs.draft-release.outputs.version }} ../CHANGELOG.md
          git add .
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git commit -a -m "update docs for develop branch"
          git push origin gh-pages
      